# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_Dialog(object):

    dangNhap = 0

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(379, 221)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 90, 71, 16))
        self.label.setObjectName("label")
        self.txtUser = QtWidgets.QLineEdit(Dialog)
        self.txtUser.setGeometry(QtCore.QRect(120, 90, 191, 20))
        self.txtUser.setObjectName("txtUser")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 71, 16))
        self.label_2.setObjectName("label_2")
        self.txtPass = QtWidgets.QLineEdit(Dialog)
        self.txtPass.setGeometry(QtCore.QRect(120, 120, 191, 20))
        self.txtPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPass.setObjectName("txtPass")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(130, 30, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btnLogin = QtWidgets.QPushButton(Dialog)
        self.btnLogin.setGeometry(QtCore.QRect(90, 160, 71, 41))
        self.btnLogin.setObjectName("btnLogin")
        self.btnReset = QtWidgets.QPushButton(Dialog)
        self.btnReset.setGeometry(QtCore.QRect(210, 160, 71, 41))
        self.btnReset.setObjectName("btnReset")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Đăng nhập"))
        self.label.setText(_translate("Dialog", "Tài khoản:"))
        self.txtUser.setPlaceholderText(_translate("Dialog", "Nhập tài khoản"))
        self.label_2.setText(_translate("Dialog", "Mật khẩu:"))
        self.txtPass.setPlaceholderText(_translate("Dialog", "Nhập mật khẩu"))
        self.label_3.setText(_translate("Dialog", "ĐĂNG NHẬP"))
        self.btnLogin.setText(_translate("Dialog", "Đăng nhập"))
        self.btnReset.setText(_translate("Dialog", "Nhập lại"))

        self.btnReset.clicked.connect(self.reset)
        self.btnLogin.clicked.connect(lambda: self.log(Dialog))

    def log(self, dlg):
        if self.txtUser.text() == "admin" and self.txtPass.text() == "admin":
            print("Dang nhap thanh cong")
            self.dangNhap = 1
            dlg.close()
        else:
            print("fail")
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setWindowTitle("Có cái gì sai sai")
            msg.setText("Sai tài khoản hoặc mật khẩu")
            msg.setStandardButtons(QMessageBox.Ok | QMessageBox.No)

            result = msg.exec_()
            if result == QMessageBox.Ok:
                print("Nguoi dung bam ok")
            elif result == QMessageBox.No:
                print("Nguoi dung bam NO")

    def reset(self):
        self.txtUser.setText("")
        self.txtPass.setText("")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
